swagger: '2.0'
info:
  version: "1.2"
  title: 'Inventory Management'
  description: 'Handles inventory management'
paths: 
  /item:
    get:
      summary: retrieves item by offest
      operationId: app.get_item_by_offset
      description: no idea yet
      produces:
      - application/json
      parameters:
        - in: query
          name: offset
          required: true
          type: integer
      responses:
        200:
          description: current stats
          schema:
            $ref: '#/definitions/ItemOffset'
        404:
          description: cannot find item
  /order:
    get:
      summary: retrieve item by quantity
      operationId: app.get_order_by_quantity
      description: grabs items with a quantity greater or equal to parameter
      produces:
      - application/json
      parameters:
        - in: query
          name: quantity
          required: true
          type: integer
        - in: query
          name: ordered_item
          required: true
          type: string
      responses:
        200:
          description: all items equal to or above specified quantity
          schema:
            $ref: '#/definitions/OrdersByQuantity'
        404:
          description: cannot find orders
definitions:
  ItemOffset:
    type: object
    required:
      - ordered_item
    properties:
      ordered_item:
        type: string
        example: apple
  OrdersByQuantity:
    type: object
    required:
      - quantity
      - ordered_item
    properties:
      quantity:
        type: integer
        example: 2
      ordered_item:
        type: string
        example: apple